steps:
- name: 'docker'
  args: ['build', '-t', 'gcr.io/lyrical-virtue-446215-s6/docker-app', '.']
- name: 'docker'
  args: ['push', 'gcr.io/lyrical-virtue-446215-s6/docker-app']
logsBucket: 'gs://tfx_logs'
options:
  logging: GCS_ONLY


  