steps:
- name: 'gcr.io/cloudbuilders/docker'
  args: ['build', '-t', 'gcr.io/kubflow-tfx/docker-app', '.']
- name: 'gcr.io/cloudbuilders/docker'
  args: ['push', 'gcr.io/kubflow-tfx/docker-app']
logsBucket: 'gs://tfx_logs'
options:
  logging: GCS_ONLY


  